# Generated by Django 4.1.4 on 2023-01-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='uploads/profile_pictures/default_image', upload_to='uploads/profile_pictures'),
        ),
    ]
