# Generated by Django 4.1.4 on 2023-01-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='uploads/profile_pictures/default_image/default_profile_image.png', upload_to='uploads/profile_pictures'),
        ),
    ]
