# Generated by Django 4.1 on 2022-12-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='category',
            new_name='instituition',
        ),
    ]
