# Generated by Django 4.1.4 on 2023-01-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_property_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
