# Generated by Django 4.1.4 on 2023-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_location_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(choices=[(10000, 10000), (20000, 20000), (30000, 30000), (40000, 40000), (50000, 50000), (60000, 60000), (70000, 70000), (80000, 80000), (90000, 90000), (100000, 100000), (120000, 120000), (140000, 140000), (160000, 160000), (180000, 180000), (200000, 200000)]),
        ),
    ]
